web-admin/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::name('admin.')->middleware('auth')->group(function () {
    Route::get('/', function () {
        return view('pages.dashboard');
    });

//    Route::get('/profile','UserController');

    Route::name('slider.')->group(function () {
        Route::get('/slider', 'SliderController@index')->name('list');
        Route::get('/slider/add', 'SliderController@viewForm')->name('add');
        Route::post('/slider/add', 'SliderController@store')->name('add');
        Route::get('/slider/edit/{id}', 'SliderController@viewForm')->name('edit');
        Route::post('/slider/edit/{id}', 'SliderController@update')->name('edit');
        Route::get('/slider/delete/{id}','SliderController@delete')->name('delete');
    });

    Route::name('update.')->group(function () {
        Route::get('/update', 'UpdateController@index')->name('list');
        Route::get('/update/add', 'UpdateController@viewForm')->name('add');
        Route::post('/update/add', 'UpdateController@store')->name('add');
        Route::get('/update/edit/{id}', 'UpdateController@viewForm')->name('edit');
        Route::post('/update/edit/{id}', 'UpdateController@update')->name('edit');
        Route::get('/update/delete/{id}','UpdateController@delete')->name('delete');
    });

    Route::name('news.')->group(function () {
        Route::get('/news', 'NewsController@index')->name('list');
        Route::get('/news/add', 'NewsController@viewForm')->name('add');
        Route::post('/news/add', 'NewsController@store')->name('add');
        Route::get('/news/edit/{id}', 'NewsController@viewForm')->name('edit');
        Route::post('/news/edit/{id}', 'NewsController@update')->name('edit');
        Route::get('/news/delete/{id}','NewsController@delete')->name('delete');
    });

    Route::name('testimonial.')->group(function () {
        Route::get('/testimonial', 'TestimonialController@index')->name('list');
        Route::get('/testimonial/add', 'TestimonialController@viewForm')->name('add');
        Route::post('/testimonial/add', 'TestimonialController@store')->name('add');
        Route::get('/testimonial/edit/{id}', 'TestimonialController@viewForm')->name('edit');
        Route::post('/testimonial/edit/{id}', 'TestimonialController@update')->name('edit');
        Route::get('/testimonial/delete/{id}','TestimonialController@delete')->name('delete');
    });

    Route::name('galleries.')->group(function () {
        Route::get('/galleries', 'GalleryController@index')->name('list');
        Route::get('/galleries/add', 'GalleryController@viewForm')->name('add');
        Route::post('/galleries/add', 'GalleryController@store')->name('add');
        Route::get('/galleries/edit/{id}', 'GalleryController@viewForm')->name('edit');
        Route::post('/galleries/edit/{id}', 'GalleryController@update')->name('edit');
        Route::get('/galleries/delete/{id}','GalleryController@delete')->name('delete');
    });

});

//    Route::resource('social', 'NewsController');

/*
web route
*/

Route::get('','WebController@home');
Route::get('/index','WebController@home');
Route::get('/applyNow','WebController@applyNow');
Route::get('/kanfedMeritScholarship','WebController@kanfedMeritScholarship');
Route::get('/Curriculum','WebController@Curriculum');
Route::get('/admissionDetails','WebController@admissionDetails');
Route::get('/lisfordInternational','WebController@lisfordInternational');
Route::get('/visionandMission','WebController@visionandMission');
Route::get('/promoters','WebController@promoters');
Route::get('/rulesandRegulations','WebController@rulesandRegulations');
Route::get('/sendMessage','WebController@sendMessage');
Route::get('/academicsEthos','WebController@academicsEthos');
Route::get('/addonCourses','WebController@addonCourses');
Route::get('/reportingandProgress','WebController@reportingandProgress');
Route::get('/results','WebController@results');
Route::get('/library','WebController@library');
Route::get('/departments','WebController@departments');
Route::get('/coCurricular','WebController@coCurricular');
Route::get('/socialResponsibility','WebController@socialResponsibility');
Route::get('/career','WebController@career');
Route::get('/gallery','WebController@gallery');
Route::get('/newsandEvents','WebController@newsandEvents');
Route::get('/contactUs','WebController@contactUs');
Route::get('/prayerandSchoolSong','WebController@prayerandSchoolSong');
Route::get('/feeStructure','WebController@feeStructure');

web-admin/app/Gallery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gallery extends Model
{
    protected $fillable = ['name', 'image_path'];
}

web-admin/app/Http/Controllers/GalleryController.php
<?php

namespace App\Http\Controllers;

use App\Gallery;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class GalleryController extends Controller
{
    public function index()
    {
        $gallery = Gallery::all();
        return view('pages.gallery.list', compact('gallery'));
    }

    public function viewForm($id=null)
    {
        if ($id == null) {
            return view('pages.gallery.addOrEdit');
        }else{
            $gallery = Gallery::findOrFail($id);
            return view('pages.gallery.addOrEdit', ['gallery' => $gallery]);
        }
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|max:255',
            'file' => 'file|required',
        ]);

        if ($path = $request->file->store('public')) {
            $gallery = new Gallery($request->all());
            $gallery->image_path = $path;
            if ($gallery->save()) {
                return redirect()->route('admin.galleries.list')->with(['smsg' => 'Gallery added succefully.', 'heading' => 'Success!']);
            }
        }
        return redirect()->route('admin.galleries.list')->with(['emsg' => 'Try Again later', 'heading' => 'Warning!']);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|max:255',
            'file' => 'file|required',
        ]);
        $gallery = Gallery::findOrFail($id);

        if (isset($request->file) ){
            if ($path = $request->file->store('public')) {
                $gallery->image_path = $path;
            }
        }

        if ($gallery->update($request->all())) {
            return redirect()->route('admin.galleries.list')->with(['smsg' => 'Record Updated', 'heading' => 'Updated!']);
        }

        return redirect()->route('admin.galleries.list')->with(['emsg' => 'Try Again later', 'heading' => 'Warning!']);
    }


    public function delete($id)
    {
        $gallery = Gallery::findOrFail($id);
        if (Gallery::destroy($id)) {
            Storage::delete($gallery->image_path);
        }
        return redirect()->back()->with(['smsg' => 'Deleted success', 'heading' => 'Deleted!']);
    }
}

web-admin/resources/views/pages/gallery/addOrEdit.blade.php
@section('include-style')
    <link href="{{asset('css/plugins/jasny/jasny-bootstrap.min.css')}}" rel="stylesheet">
@stop

@extends('layouts.app')
@section('title', 'gallery')

@section('content')
    <div class="row" >
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Add gallery image</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form action="" class="form-horizontal"  enctype="multipart/form-data" method="POST">
                        {{csrf_field()}}
                        <input type="hidden" name="type" value="gallery"/>
                        <div class="form-group">
                            <label class="col-lg-2 control-label">Name<span class="text-danger">*</span></label>
                            <div class="col-lg-8">
                                <input class="form-control" name="name" id="name" value="{{old('name', ($gallery->name ?? null))}}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-2 control-label">Image<span class="text-danger">*</span></label>
                            <div class="col-lg-8">

                                <div class="fileinput fileinput-new input-group" data-provides="fileinput">
                                    @isset($gallery)
                                        <div class="form-control" data-trigger="fileinput">
                                            <i class="glyphicon glyphicon-file fileinput-exists"></i>
                                            <span class="fileinput-filename">{{basename($gallery->image_path)}}</span>
                                        </div>
                                    @else
                                    <div class="form-control" data-trigger="fileinput">
                                        <i class="glyphicon glyphicon-file fileinput-exists"></i>
                                        <span class="fileinput-filename"></span>
                                    </div>
                                    @endisset

                                    <span class="input-group-addon btn btn-default btn-file">
                                        <span class="fileinput-new">Select file</span>
                                        <span class="fileinput-exists">Change</span>
                                        <input type="file" name="file"/>
                                    </span>
                                    <a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput" id="fileinput-exists">Remove</a>
                                </div>
                                {{--<span class="help-block m-b-none" id="file-helper-text">image should be 500 * 500.</span>--}}
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="lightBoxGallery">
                                @if(isset($gallery))
                                    <img src="{{asset('storage/'.basename($gallery->image_path))}}" id="preview-image" width="100px" height="100px">
                                @else
                                    <img src="{{asset('img/no-preview-available.png')}}" id="preview-image" width="100px" height="100px">
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-lg-12 text-center">
                                <button class="btn btn-success" type="submit" id="submit-all">Submit</button>
                                <a class="btn btn-danger" href="{{route('admin.galleries.list')}}">Cancel</a>
                            </div>
                        </div>
                    </form>
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>


@stop
@section('include-script')
    <script src="{{asset('js/plugins/dataTables/datatables.min.js')}}"></script>
    <!-- Jasny -->
    <script src="{{asset('js/plugins/jasny/jasny-bootstrap.min.js')}}"></script>
@stop
@section('custom-scripts')
<script>
    $(document).ready(function(){
        $('.dataTables-example').DataTable({
            pageLength: 25,
            responsive: true,
            dom: '<"html5buttons"B>gl<"#add-btn.col-xs-12 col-sm-3 col-md-3 text-center">ft<"col-sm-3"i>p',
            buttons: [
                { extend: 'copy'},
                {extend: 'csv'},
                {extend: 'excel', title: 'ExampleFile'},
                {extend: 'pdf', title: 'ExampleFile'},

                {extend: 'print',
                 customize: function (win){
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');

                        $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                }
                }
            ],
            "initComplete": function(settings, json) {
                var html = '<a class="btn btn-primary btn-sm" type="button" href="{{route('admin.galleries.add')}}" ><i class="fa fa-plus"></i>Add New Gallery</a>';
                 $("#add-btn")
                         .html(html);
              }
        });
    });

     $("#select_image").change(function() {
//      readURL(this,'preview-image');
      validateDimension(this,'preview-image',500,500);
    });
     $("#fileinput-exists").click(function() {
        $('#preview-image').attr('src', '{{asset('img/no-preview-available.png')}}');
    });



</script>

@stop

web-admin/resources/views/pages/gallery/list.blade.php
@section('include-style')
    <link href="{{asset('css/plugins/dataTables/datatables.min.css')}}" rel="stylesheet">
@stop

@extends('layouts.app')
@section('title', 'gallery')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>List all gallery images</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover dataTables-example" >
                        <thead>
                        <tr>
                            <th>$</th>
                            <th>Name</th>
                            <th>Image</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($gallery as $key => $value)
                        <tr>
                            <td>{{$key+1}}</td>
                            <td>{{$value->name}}</td>
                            <td><img src="{{asset('storage/'.basename($value->image_path))}}" alt="" width="50px" height="50px"/></td>
                            <td class="center">
                                <div class="btn-group btn-group-xs" role="group">
                                    <a class="btn btn-info" id="editGallery" href="{{route('admin.galleries.edit',$value->id)}}"><i class="fa fa-pencil"></i></a>
                                    <a class="btn btn-danger" id="removeThis" href="{{route('admin.galleries.delete',$value->id)}}"><i class="fa fa-trash-o"></i></a>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                        </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop
@section('include-script')
    <script src="js/plugins/dataTables/datatables.min.js"></script>
@stop
@section('custom-scripts')
<script>
    $(document).ready(function(){
        $('.dataTables-example').DataTable({
            pageLength: 25,
            responsive: true,
            dom: '<"html5buttons"B>gl<"#add-btn.col-xs-12 col-sm-3 col-md-3 text-center">ft<"col-sm-3"i>p',
            buttons: [
                { extend: 'copy'},
                {extend: 'csv'},
                {extend: 'excel', title: 'ExampleFile'},
                {extend: 'pdf', title: 'ExampleFile'},

                {extend: 'print',
                 customize: function (win){
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');

                        $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                }
                }
            ],
            "initComplete": function(settings, json) {
                var html = '<a class="btn btn-primary btn-sm" type="button" href="{{route('admin.galleries.add')}}" ><i class="fa fa-plus"></i>Add New Gallery</a>';
                 $("#add-btn")
                         .html(html);
              }
        });
    });



</script>

@stop