web-admin/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::name('admin.')->middleware('auth')->group(function () {
    Route::get('/', function () {
        return view('pages.dashboard');
    });

//    Route::get('/profile','UserController');

    Route::name('slider.')->group(function () {
        Route::get('/slider', 'SliderController@index')->name('list');
        Route::get('/slider/add', 'SliderController@viewForm')->name('add');
        Route::post('/slider/add', 'SliderController@store')->name('add');
        Route::get('/slider/edit/{id}', 'SliderController@viewForm')->name('edit');
        Route::post('/slider/edit/{id}', 'SliderController@update')->name('edit');
        Route::get('/slider/delete/{id}','SliderController@delete')->name('delete');
    });

    Route::name('update.')->group(function () {
        Route::get('/update', 'UpdateController@index')->name('list');
        Route::get('/update/add', 'UpdateController@viewForm')->name('add');
        Route::post('/update/add', 'UpdateController@store')->name('add');
        Route::get('/update/edit/{id}', 'UpdateController@viewForm')->name('edit');
        Route::post('/update/edit/{id}', 'UpdateController@update')->name('edit');
        Route::get('/update/delete/{id}','UpdateController@delete')->name('delete');
    });

    Route::name('news.')->group(function () {
        Route::get('/news', 'NewsController@index')->name('list');
        Route::get('/news/add', 'NewsController@viewForm')->name('add');
        Route::post('/news/add', 'NewsController@store')->name('add');
        Route::get('/news/edit/{id}', 'NewsController@viewForm')->name('edit');
        Route::post('/news/edit/{id}', 'NewsController@update')->name('edit');
        Route::get('/news/delete/{id}','NewsController@delete')->name('delete');
    });

    Route::name('testimonial.')->group(function () {
        Route::get('/testimonial', 'TestimonialController@index')->name('list');
        Route::get('/testimonial/add', 'TestimonialController@viewForm')->name('add');
        Route::post('/testimonial/add', 'TestimonialController@store')->name('add');
        Route::get('/testimonial/edit/{id}', 'TestimonialController@viewForm')->name('edit');
        Route::post('/testimonial/edit/{id}', 'TestimonialController@update')->name('edit');
        Route::get('/testimonial/delete/{id}','TestimonialController@delete')->name('delete');
    });

    Route::name('galleries.')->group(function () {
        Route::get('/galleries', 'GalleryController@index')->name('list');
        Route::get('/galleries/add', 'GalleryController@viewForm')->name('add');
        Route::post('/galleries/add', 'GalleryController@store')->name('add');
        Route::get('/galleries/edit/{id}', 'GalleryController@viewForm')->name('edit');
        Route::post('/galleries/edit/{id}', 'GalleryController@update')->name('edit');
        Route::get('/galleries/delete/{id}','GalleryController@delete')->name('delete');
    });

});

//    Route::resource('social', 'NewsController');

/*
web route
*/

Route::get('','WebController@home');
Route::get('/index','WebController@home');
Route::get('/applyNow','WebController@applyNow');
Route::get('/kanfedMeritScholarship','WebController@kanfedMeritScholarship');
Route::get('/Curriculum','WebController@Curriculum');
Route::get('/admissionDetails','WebController@admissionDetails');
Route::get('/lisfordInternational','WebController@lisfordInternational');
Route::get('/visionandMission','WebController@visionandMission');
Route::get('/promoters','WebController@promoters');
Route::get('/rulesandRegulations','WebController@rulesandRegulations');
Route::get('/sendMessage','WebController@sendMessage');
Route::get('/academicsEthos','WebController@academicsEthos');
Route::get('/addonCourses','WebController@addonCourses');
Route::get('/reportingandProgress','WebController@reportingandProgress');
Route::get('/results','WebController@results');
Route::get('/library','WebController@library');
Route::get('/departments','WebController@departments');
Route::get('/coCurricular','WebController@coCurricular');
Route::get('/socialResponsibility','WebController@socialResponsibility');
Route::get('/career','WebController@career');
Route::get('/gallery','WebController@gallery');
Route::get('/newsandEvents','WebController@newsandEvents');
Route::get('/contactUs','WebController@contactUs');
Route::get('/prayerandSchoolSong','WebController@prayerandSchoolSong');
Route::get('/feeStructure','WebController@feeStructure');

web-admin/app/Update.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Update extends Model
{
    protected $fillable = ['content'];
}

web-admin/app/Http/Controllers/UpdateController.php
<?php

namespace App\Http\Controllers;

use App\Update;
use Illuminate\Http\Request;

class UpdateController extends Controller
{
    public function index()
    {
        $update = Update::all();
        return view('pages.update.list', compact('update'));
    }

    public function viewForm($id=null)
    {
        if ($id == null) {
            return view('pages.update.addOrEdit');
        }else{
            $update = Update::findOrFail($id);
            return view('pages.update.addOrEdit', ['update' => $update]);
        }
    }

    public function store(Request $request)
    {
        $request->validate([
            'content' => 'required',
        ]);
        $update = new Update($request->all());

        if ($update->save()) {
            return redirect()->route('admin.update.list')->with(['smsg' => 'Update added succefully.', 'heading' => 'Success!']);
        }

        return redirect()->route('admin.update.list')->with(['emsg' => 'Try Again later', 'heading' => 'Warning!']);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'content' => 'required',
        ]);
        $update = Update::findOrFail($id);
        if ($update->update($request->all())) {
            return redirect()->route('admin.update.list')->with(['smsg' => 'Record Updated', 'heading' => 'Updated!']);
        }

        return redirect()->route('admin.update.list')->with(['emsg' => 'Try Again later', 'heading' => 'Warning!']);
    }


    public function delete($id)
    {
        if (Update::destroy($id)) {
            return redirect()->route('admin.update.list')->with(['smsg' => 'Record Deleted', 'heading' => 'Deleted!']);
        }
    }
}

web-admin/resources/views/pages/update/addOrEdit.blade.php
@section('include-style')
    <link href="{{asset('css/plugins/jasny/jasny-bootstrap.min.css')}}" rel="stylesheet">
@stop

@extends('layouts.app')
@section('title', 'update')

@section('content')
    <div class="row" >
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Add update</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form action="" class="form-horizontal"  enctype="multipart/form-data" method="POST">
                        {{csrf_field()}}
                        <input type="hidden" name="type" value="update"/>
                        <div class="form-group">
                            <label class="col-lg-2 control-label">Content <span class="text-danger">*</span></label>
                            <div class="col-lg-8">
                                <textarea class="form-control" name="content" id="content">@isset($update){{$update->content}}@endisset</textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-lg-10 text-center">
                                <button class="btn btn-success" type="submit" id="submit-all">Submit</button>
                                <a class="btn btn-danger" href="{{route('admin.update.list')}}">Cancel</a>
                            </div>
                        </div>
                    </form>
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>


@stop
@section('include-script')
    <script src="{{asset('js/plugins/dataTables/datatables.min.js')}}"></script>
    <!-- Jasny -->
    <script src="{{asset('js/plugins/jasny/jasny-bootstrap.min.js')}}"></script>
@stop
@section('custom-scripts')
<script>
    $(document).ready(function(){
        $('.dataTables-example').DataTable({
            pageLength: 25,
            responsive: true,
            dom: '<"html5buttons"B>gl<"#add-btn.col-xs-12 col-sm-3 col-md-3 text-center">ft<"col-sm-3"i>p',
            buttons: [
                { extend: 'copy'},
                {extend: 'csv'},
                {extend: 'excel', title: 'ExampleFile'},
                {extend: 'pdf', title: 'ExampleFile'},

                {extend: 'print',
                 customize: function (win){
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');

                        $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                }
                }
            ],
            "initComplete": function(settings, json) {
                var html = '<a class="btn btn-primary btn-sm" type="button" href="{{route('admin.update.add')}}" ><i class="fa fa-plus"></i>Add New Update</a>';
                 $("#add-btn")
                         .html(html);
              }
        });
    });

     $("#select_image").change(function() {
//      readURL(this,'preview-image');
      validateDimension(this,'preview-image',500,500);
    });
     $("#fileinput-exists").click(function() {
        $('#preview-image').attr('src', '{{asset('img/no-preview-available.png')}}');
    });



</script>

@stop

web-admin/resources/views/pages/update/list.blade.php
@section('include-style')
    <link href="{{asset('css/plugins/dataTables/datatables.min.css')}}" rel="stylesheet">
@stop

@extends('layouts.app')
@section('title', 'update')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>List all updates</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover dataTables-example" >
                        <thead>
                        <tr>
                            <th>$</th>
                            <th>Content</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($update as $key => $value)
                        <tr>
                            <td>{{$key+1}}</td>
                            <td>{{$value->content}}</td>
                            <td class="center">
                                <div class="btn-group btn-group-xs" role="group">
                                    <a class="btn btn-info" id="editUpdate" href="{{route('admin.update.edit',$value->id)}}"><i class="fa fa-pencil"></i></a>
                                    <a class="btn btn-danger" id="removeThis" href="{{route('admin.update.delete',$value->id)}}"><i class="fa fa-trash-o"></i></a>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                        </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop
@section('include-script')
    <script src="js/plugins/dataTables/datatables.min.js"></script>
@stop
@section('custom-scripts')
<script>
    $(document).ready(function(){
        $('.dataTables-example').DataTable({
            pageLength: 25,
            responsive: true,
            dom: '<"html5buttons"B>gl<"#add-btn.col-xs-12 col-sm-3 col-md-3 text-center">ft<"col-sm-3"i>p',
            buttons: [
                { extend: 'copy'},
                {extend: 'csv'},
                {extend: 'excel', title: 'ExampleFile'},
                {extend: 'pdf', title: 'ExampleFile'},

                {extend: 'print',
                 customize: function (win){
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');

                        $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                }
                }
            ],
            "initComplete": function(settings, json) {
                var html = '<a class="btn btn-primary btn-sm" type="button" href="{{route('admin.update.add')}}" ><i class="fa fa-plus"></i>Add New Update</a>';
                 $("#add-btn")
                         .html(html);
              }
        });
    });



</script>

@stop