web-admin/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::name('admin.')->middleware('auth')->group(function () {
    Route::get('/', function () {
        return view('pages.dashboard');
    });

//    Route::get('/profile','UserController');

    Route::name('slider.')->group(function () {
        Route::get('/slider', 'SliderController@index')->name('list');
        Route::get('/slider/add', 'SliderController@viewForm')->name('add');
        Route::post('/slider/add', 'SliderController@store')->name('add');
        Route::get('/slider/edit/{id}', 'SliderController@viewForm')->name('edit');
        Route::post('/slider/edit/{id}', 'SliderController@update')->name('edit');
        Route::get('/slider/delete/{id}','SliderController@delete')->name('delete');
    });

    Route::name('update.')->group(function () {
        Route::get('/update', 'UpdateController@index')->name('list');
        Route::get('/update/add', 'UpdateController@viewForm')->name('add');
        Route::post('/update/add', 'UpdateController@store')->name('add');
        Route::get('/update/edit/{id}', 'UpdateController@viewForm')->name('edit');
        Route::post('/update/edit/{id}', 'UpdateController@update')->name('edit');
        Route::get('/update/delete/{id}','UpdateController@delete')->name('delete');
    });

    Route::name('news.')->group(function () {
        Route::get('/news', 'NewsController@index')->name('list');
        Route::get('/news/add', 'NewsController@viewForm')->name('add');
        Route::post('/news/add', 'NewsController@store')->name('add');
        Route::get('/news/edit/{id}', 'NewsController@viewForm')->name('edit');
        Route::post('/news/edit/{id}', 'NewsController@update')->name('edit');
        Route::get('/news/delete/{id}','NewsController@delete')->name('delete');
    });

    Route::name('testimonial.')->group(function () {
        Route::get('/testimonial', 'TestimonialController@index')->name('list');
        Route::get('/testimonial/add', 'TestimonialController@viewForm')->name('add');
        Route::post('/testimonial/add', 'TestimonialController@store')->name('add');
        Route::get('/testimonial/edit/{id}', 'TestimonialController@viewForm')->name('edit');
        Route::post('/testimonial/edit/{id}', 'TestimonialController@update')->name('edit');
        Route::get('/testimonial/delete/{id}','TestimonialController@delete')->name('delete');
    });

    Route::name('galleries.')->group(function () {
        Route::get('/galleries', 'GalleryController@index')->name('list');
        Route::get('/galleries/add', 'GalleryController@viewForm')->name('add');
        Route::post('/galleries/add', 'GalleryController@store')->name('add');
        Route::get('/galleries/edit/{id}', 'GalleryController@viewForm')->name('edit');
        Route::post('/galleries/edit/{id}', 'GalleryController@update')->name('edit');
        Route::get('/galleries/delete/{id}','GalleryController@delete')->name('delete');
    });

});

//    Route::resource('social', 'NewsController');

/*
web route
*/

Route::get('','WebController@home');
Route::get('/index','WebController@home');
Route::get('/applyNow','WebController@applyNow');
Route::get('/kanfedMeritScholarship','WebController@kanfedMeritScholarship');
Route::get('/Curriculum','WebController@Curriculum');
Route::get('/admissionDetails','WebController@admissionDetails');
Route::get('/lisfordInternational','WebController@lisfordInternational');
Route::get('/visionandMission','WebController@visionandMission');
Route::get('/promoters','WebController@promoters');
Route::get('/rulesandRegulations','WebController@rulesandRegulations');
Route::get('/sendMessage','WebController@sendMessage');
Route::get('/academicsEthos','WebController@academicsEthos');
Route::get('/addonCourses','WebController@addonCourses');
Route::get('/reportingandProgress','WebController@reportingandProgress');
Route::get('/results','WebController@results');
Route::get('/library','WebController@library');
Route::get('/departments','WebController@departments');
Route::get('/coCurricular','WebController@coCurricular');
Route::get('/socialResponsibility','WebController@socialResponsibility');
Route::get('/career','WebController@career');
Route::get('/gallery','WebController@gallery');
Route::get('/newsandEvents','WebController@newsandEvents');
Route::get('/contactUs','WebController@contactUs');
Route::get('/prayerandSchoolSong','WebController@prayerandSchoolSong');
Route::get('/feeStructure','WebController@feeStructure');

web-admin/resources/views/includes/footer.blade.php
    <div class="pull-right text-right">
        Powered by <a href="http://www.cloudbery.com/" target="_blank"><img style="width: 33%;" src="http://www.cloudbery.com/cloudberyweb/assets/img/logo.png" alt="cloudbery solutions"/></a>
    </div>
    <div>
        <strong>Copyright</strong> Lisford International &copy; {{date("Y",strtotime("-1 year")).'-'.date("Y")}}
    </div>

web-admin/resources/views/includes/head.blade.php
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Lisford Web-admin - @yield('title')</title>

    <link href="{{asset('css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('font-awesome/css/font-awesome.css')}}" rel="stylesheet">

    <!-- Toastr style -->
    <link href="{{asset('css/plugins/toastr/toastr.min.css')}}" rel="stylesheet">

    <!-- Gritter -->
    <link href="{{asset('js/plugins/gritter/jquery.gritter.css')}}" rel="stylesheet">

    <!-- Sweet Alert -->
    <link href="{{asset('css/plugins/sweetalert/sweetalert.css')}}" rel="stylesheet">

    <link href="{{asset('css/animate.css')}}" rel="stylesheet">
    @yield('include-style')
    <link href="{{asset('css/style.css')}}" rel="stylesheet">

web-admin/resources/views/includes/header.blade.php
<nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                     <div class="navbar-header">
                         <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                         <form role="search" class="navbar-form-custom" action="search_results.html">
                             <div class="form-group">
                                 <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
                             </div>
                         </form>
                     </div>
                     <ul class="nav navbar-top-links navbar-right">
                         <li>
                             <span class="m-r-sm text-muted welcome-message">Welcome to Lisford International School Dashboard</span>
                         </li>
                         <li class="dropdown">
                             <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                                 <i class="fa fa-envelope"></i>  <span class="label label-warning">16</span>
                             </a>
                             <ul class="dropdown-menu dropdown-messages">
                                 <li>
                                     <div class="dropdown-messages-box">
                                         <a href="profile.html" class="pull-left">
                                             <img alt="image" class="img-circle" src="img/a7.jpg">
                                         </a>
                                         <div class="media-body">
                                             <small class="pull-right">46h ago</small>
                                             <strong>Mike Loreipsum</strong> started following <strong>Monica Smith</strong>. <br>
                                             <small class="text-muted">3 days ago at 7:58 pm - 10.06.2014</small>
                                         </div>
                                     </div>
                                 </li>
                                 <li class="divider"></li>
                                 <li>
                                     <div class="dropdown-messages-box">
                                         <a href="profile.html" class="pull-left">
                                             <img alt="image" class="img-circle" src="img/a4.jpg">
                                         </a>
                                         <div class="media-body ">
                                             <small class="pull-right text-navy">5h ago</small>
                                             <strong>Chris Johnatan Overtunk</strong> started following <strong>Monica Smith</strong>. <br>
                                             <small class="text-muted">Yesterday 1:21 pm - 11.06.2014</small>
                                         </div>
                                     </div>
                                 </li>
                                 <li class="divider"></li>
                                 <li>
                                     <div class="dropdown-messages-box">
                                         <a href="profile.html" class="pull-left">
                                             <img alt="image" class="img-circle" src="img/profile.jpg">
                                         </a>
                                         <div class="media-body ">
                                             <small class="pull-right">23h ago</small>
                                             <strong>Monica Smith</strong> love <strong>Kim Smith</strong>. <br>
                                             <small class="text-muted">2 days ago at 2:30 am - 11.06.2014</small>
                                         </div>
                                     </div>
                                 </li>
                                 <li class="divider"></li>
                                 <li>
                                     <div class="text-center link-block">
                                         <a href="mailbox.html">
                                             <i class="fa fa-envelope"></i> <strong>Read All Messages</strong>
                                         </a>
                                     </div>
                                 </li>
                             </ul>
                         </li>
                         <li class="dropdown">
                             <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                                 <i class="fa fa-bell"></i>  <span class="label label-primary">8</span>
                             </a>
                             <ul class="dropdown-menu dropdown-alerts">
                                 <li>
                                     <a href="mailbox.html">
                                         <div>
                                             <i class="fa fa-envelope fa-fw"></i> You have 16 messages
                                             <span class="pull-right text-muted small">4 minutes ago</span>
                                         </div>
                                     </a>
                                 </li>
                                 <li class="divider"></li>
                                 <li>
                                     <a href="profile.html">
                                         <div>
                                             <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                             <span class="pull-right text-muted small">12 minutes ago</span>
                                         </div>
                                     </a>
                                 </li>
                                 <li class="divider"></li>
                                 <li>
                                     <a href="grid_options.html">
                                         <div>
                                             <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                             <span class="pull-right text-muted small">4 minutes ago</span>
                                         </div>
                                     </a>
                                 </li>
                                 <li class="divider"></li>
                                 <li>
                                     <div class="text-center link-block">
                                         <a href="notifications.html">
                                             <strong>See All Alerts</strong>
                                             <i class="fa fa-angle-right"></i>
                                         </a>
                                     </div>
                                 </li>
                             </ul>
                         </li>


                         <li>
                             {{ csrf_field() }}
                                               <a onclick="document.getElementById('myform').submit();"><i class="fa fa-sign-out"></i> Log out</a>
                         </li>
                         <li>
                             <a class="right-sidebar-toggle">
                                 <i class="fa fa-tasks"></i>
                             </a>
                         </li>
                     </ul>

                 </nav>

web-admin/resources/views/includes/scripts.blade.php
<!-- Mainly scripts -->
 <script src="{{asset('js/jquery-3.1.1.min.js')}}"></script>
 <script src="{{asset('js/bootstrap.min.js')}}"></script>
 <script src="{{asset('js/plugins/metisMenu/jquery.metisMenu.js')}}"></script>
 <script src="{{asset('js/plugins/slimscroll/jquery.slimscroll.min.js')}}"></script>

 <!-- Custom and plugin javascript -->
 <script src="{{asset('js/inspinia.js')}}"></script>
 <script src="{{asset('js/plugins/pace/pace.min.js')}}"></script>

 <script src="{{asset('js/custom.js')}}"></script>

 <!-- jQuery UI -->
 <script src="{{asset('js/plugins/jquery-ui/jquery-ui.min.js')}}"></script>

 <!-- Toastr -->
 <script src="{{asset('js/plugins/toastr/toastr.min.js')}}"></script>

  <!-- Sweet alert -->
 <script src="{{asset('js/plugins/sweetalert/sweetalert.min.js')}}"></script>

 <script>
    function readURL(input,previewControl) {

       if (input.files && input.files[0]) {
         var reader = new FileReader();

         reader.onload = function(e)
         {
           $('#'+previewControl).attr('src', e.target.result);
         };

         reader.readAsDataURL(input.files[0]);
       }
     }


     $('#removeThis').click(function (e) {
         e.preventDefault();
         var url= $(this).attr("href");
         swal({
             title: "Are you sure?",
             text: "You will not be able to recover this data!",
             type: "warning",
             showCancelButton: true,
             confirmButtonColor: "#DD6B55",
             confirmButtonText: "Yes, delete it!",
             closeOnConfirm: false
         }, function () {
             window.location=url;

         });
     });

    @if(session()->has('smsg'))
        swal("{{session()->get('heading')}}", '{{session()->get('smsg')}}', "success");
    @endif

    @if(session()->has('emsg'))
        swal("{{session()->get('heading')}}", '{{session()->get('smsg')}}', "error");
    @endif

     function validateDimension(input, ele = '', width = 0, height = 0) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                var image = new Image();
                image.src = e.target.result;

                image.onload = function () {
                    if (width != 0 && height != 0) {
                        if (this.width > width || this.height > height) {
                            var $el = $(input);
                            $el.wrap('<form>').closest('form').get(0).reset();
                            $el.unwrap();
                            swal("Warning", 'Selected image was too long. Please select this ' + width + ' x ' + height + ' ratio.', "error");
                            $('#' + ele).attr('src', '');
                            $('.fileinput-filename').html('');
                        } else {
                            $('#' + ele).attr('src', e.target.result);
                            $('#file-helper-text').append('your selected image '+this.width+'w and '+this.height+'h');
                        }
                    }
                };

            };

            reader.readAsDataURL(input.files[0]);

        }
    }

 </script>


 @yield('include-script')

web-admin/resources/views/includes/sidebar.blade.php
<div class="sidebar-collapse">
 <ul class="nav metismenu" id="side-menu">
     <li class="nav-header">
         <div class="dropdown profile-element"> <span>
             <img alt="image" class="img-circle" src="img/profile_small.jpg" />
              </span>
             <a data-toggle="dropdown" class="dropdown-toggle" href="#">
             <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">Lisford International School</strong>
              </span> <span class="text-muted text-xs block">Admin <b class="caret"></b></span> </span> </a>
             <ul class="dropdown-menu animated fadeInRight m-t-xs">
                 {{--<li><a href="#">Profile</a></li>--}}
                 {{--<li><a href="contacts.html">Contacts</a></li>--}}
                 {{--<li><a href="mailbox.html">Mailbox</a></li>--}}
                 {{--<li class="divider"></li>--}}
                 <li><a onclick="document.getElementById('myform').submit();"><i class="zmdi zmdi-power"></i><span>Log Out</span></a>
                     							    <form id="myform" method="POST" action="/logout">@csrf</form></li>
             </ul>
         </div>
         <div class="logo-element">
             IN+
         </div>
     </li>
     <li class="active">
          <a href="{{route('admin.slider.list')}}"><i class="fa fa-image"></i> <span class="nav-label">Sliders</span></a>
     </li>
      <li>
          <a href="{{route('admin.update.list')}}"><i class="fa fa-bullhorn"></i> <span class="nav-label">Latest Updates</span></a>
      </li>
     <li>
          <a href="{{route('admin.testimonial.list')}}"><i class="fa fa-comments-o"></i> <span class="nav-label">Testimonial</span></a>
     </li>
     <li>
         <a href="{{route('admin.news.list')}}"><i class="fa fa-vcard-o"></i> <span class="nav-label">News and Events</span></a>
     </li>
      <li>
          <a href="{{route('admin.galleries.list')}}"><i class="fa fa-camera"></i> <span class="nav-label">Gallery</span></a>
      </li>
     {{--<li>--}}
         {{--<a href="{{route('admin.social.index',['type' => 'social'])}}"><i class="fa fa-diamond"></i> <span class="nav-label">Social</span></a>--}}
     {{--</li>--}}

     {{--<li>--}}
         {{--<a href="#"><i class="fa fa-bar-chart-o"></i> <span class="nav-label">Graphs</span><span class="fa arrow"></span></a>--}}
         {{--<ul class="nav nav-second-level collapse">--}}
             {{--<li><a href="graph_flot.html">Flot Charts</a></li>--}}
             {{--<li><a href="graph_morris.html">Morris.js Charts</a></li>--}}
             {{--<li><a href="graph_rickshaw.html">Rickshaw Charts</a></li>--}}
             {{--<li><a href="graph_chartjs.html">Chart.js</a></li>--}}
             {{--<li><a href="graph_chartist.html">Chartist</a></li>--}}
             {{--<li><a href="c3.html">c3 charts</a></li>--}}
             {{--<li><a href="graph_peity.html">Peity Charts</a></li>--}}
             {{--<li><a href="graph_sparkline.html">Sparkline Charts</a></li>--}}
         {{--</ul>--}}
     {{--</li>--}}
 </ul>

</div>